-- MySQL Script generated by MySQL Workbench
-- 05/18/15 05:10:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema microblog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `microblog` ;

-- -----------------------------------------------------
-- Schema microblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `microblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `microblog` ;

-- -----------------------------------------------------
-- Table `microblog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`user` ;

CREATE TABLE IF NOT EXISTS `microblog`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(20) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` CHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`user_extra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`user_extra` ;

CREATE TABLE IF NOT EXISTS `microblog`.`user_extra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `set_avatar` TINYINT(1) NOT NULL DEFAULT 0,
  `set_profile` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(45) NOT NULL,
  `joined` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_extra_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `microblog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`blog` ;

CREATE TABLE IF NOT EXISTS `microblog`.`blog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `text` VARCHAR(144) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_blog_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `microblog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`image` ;

CREATE TABLE IF NOT EXISTS `microblog`.`image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `blog_id`),
  INDEX `blog_id_idx` (`blog_id` ASC),
  CONSTRAINT `fk_image_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `microblog`.`blog` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`comment` ;

CREATE TABLE IF NOT EXISTS `microblog`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `src_blog_id` INT UNSIGNED NOT NULL,
  `dist_blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `src_blog_id`, `dist_blog_id`),
  INDEX `src_blog_id_idx` (`src_blog_id` ASC),
  INDEX `dist_blog_id_idx` (`dist_blog_id` ASC),
  CONSTRAINT `fk_comment_src_blog_id`
    FOREIGN KEY (`src_blog_id`)
    REFERENCES `microblog`.`blog` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_dist_blog_id`
    FOREIGN KEY (`dist_blog_id`)
    REFERENCES `microblog`.`blog` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`follow` ;

CREATE TABLE IF NOT EXISTS `microblog`.`follow` (
  `src_user_id` INT UNSIGNED NOT NULL,
  `dist_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`src_user_id`, `dist_user_id`),
  INDEX `dist_user_id_idx` (`dist_user_id` ASC),
  CONSTRAINT `fk_followers_src_user_id`
    FOREIGN KEY (`src_user_id`)
    REFERENCES `microblog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_followers_dist_user_id`
    FOREIGN KEY (`dist_user_id`)
    REFERENCES `microblog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`hash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`hash` ;

CREATE TABLE IF NOT EXISTS `microblog`.`hash` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`blog_on_hash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`blog_on_hash` ;

CREATE TABLE IF NOT EXISTS `microblog`.`blog_on_hash` (
  `hash_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`hash_id`, `blog_id`),
  INDEX `blog_id_idx` (`blog_id` ASC),
  CONSTRAINT `fk_blog_on_hash_hash_id`
    FOREIGN KEY (`hash_id`)
    REFERENCES `microblog`.`hash` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_blog_on_hash_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `microblog`.`blog` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`favorite` ;

CREATE TABLE IF NOT EXISTS `microblog`.`favorite` (
  `user_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `blog_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `blog_id_idx` (`blog_id` ASC),
  CONSTRAINT `fk_favorite_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `microblog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favorite_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `microblog`.`blog` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`reblog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `microblog`.`reblog` ;

CREATE TABLE IF NOT EXISTS `microblog`.`reblog` (
  `user_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `blog_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `blog_id_idx` (`blog_id` ASC),
  CONSTRAINT `fk_reblog_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `microblog`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reblog_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `microblog`.`blog` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
